### ISSUE TITLE
Getting No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by alberdg** [cometd/cometd-nodejs-server#10]
Hi,

I am unsuccessfully trying to connect to my cometd server and getting: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I read the javascript cometd documentation at []([]https://docs.cometd.org/current/reference/#_javascript_transports_cross_origin) but does not provide much detail for javascript. 

I have added the following configuration but still the same

```
cometd.createCometDServer({
        logLevel: 'info', // Emits logging on the console
        timeout: 10000, // Heartbeat timeout in milliseconds
        maxInterval: 15000,
        requestHeaders:{
          'Access-Control-Allow-Origin': 'http://localhost:19002'
        }
      })

```
Could you please provide some help with this?

Thanks!

**Comment by sbordet** [comment]
You are making a cross origin request to your CometD server, so you need [CORS](https://www.w3.org/TR/cors/).

There exist a [NPM cors package](https://www.npmjs.com/package/cors) to be used with Express.

The `Access-Control-Allow-Origin` is a header that should be added to the _response_.

If you're going to do CORS manually, I recommend that you do it separately from CometD, as a wrapper function that is invoked before CometD, for example:

```javascript
var http = require('http');
var cometd = require('cometd-nodejs-server');
var cometdServer = cometd.createCometDServer();
var cors = function(request, response) {
    // First CORS handling.
    // Then forward to cometdServer.handle(request, response).
}
var httpServer = http.createServer(cors);
```

Let know if that worked for you.

**Comment by alberdg** [comment]
Hi Simone,

Thanks for the prompt answer, it worked perfectly!!

Thanks!

**Comment by sbordet** [comment]
What did you use, NPM cors, or the wrapper ?
Feel free to close the issue if it's solved for you.

**Comment by alberdg** [comment]
I used the wrapper

```
this.cometdHttpServer = http.createServer((req, res) => {
        res.setHeader('Access-Control-Allow-Origin', '*')
        res.setHeader('Access-Control-Allow-Headers', 'x-requested-with,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Pragma,Cache-Control')
        this.cometd.handle(req, res)
      })
```
Did the trick so I'm closing it.

Thanks!

**Comment by sbordet** [comment]
Remember that there is a security reason for CORS and that allowing all origins may not be desirable.

**Comment by alberdg** [comment]
Yes, that was just my first test!

Thanks for the reminder
