### ISSUE TITLE
Headers in request

### ISSUE THREAD

**Issue by leenelc** [cometd/cometd-nodejs-server#14]
How do I get the headers of a message published to a channel? 

Further, in the cometd-nodejs-client, there is a requestHeaders option in the configuration which I believe sends the same header every time the cometd client publishes to the defined url. Is that true?

**Comment by sbordet** [comment]
I have updated the documentation to show how to access the `context` object, see section "Accessing Contextual Information" in [README](https://github.com/cometd/cometd-nodejs-server/blob/master/README.md).
