### ISSUE TITLE
Provide TypeScript *.d.ts files

### ISSUE THREAD

**Issue by sbordet** [cometd/cometd-nodejs-server#22]
For use with TypeScript, would be great if the server library could provide `*.d.ts` types.

**Comment by sbordet** [comment]
See also https://github.com/cometd/cometd-nodejs-client/issues/26.

**Comment by cschuff** [comment]
Hi @sbordet, 

will you have the chance to release the TypeScript definitions anytime soon? It would be of great help 🙏🏻 

Thx and BR
Chris

**Comment by sbordet** [comment]
@cschuff were you able to try them out from HEAD, by chance?

**Comment by sbordet** [comment]
@cschuff sorry for the delay, the TypeScript type definitions have been released in the latest CometD releases.
