### ISSUE TITLE
Request undefined, what am I doing wrong?

### ISSUE THREAD

**Issue by Uttam92477** [cometd/cometd-nodejs-server#23]
I have a simple single file nodejs application and I attempted to create a channel, publish to it and listen to the message. It is working as expected but, when I tried to get the request object it was **undefined**, can anyone point to me the issue with my code. More specifically what I am asking is, in a nodejs server how to ensure I use HTTP transport and not websocket.

```js
const http = require('http')
const cometd = require('cometd-nodejs-server')
const cometdServer = cometd.createCometDServer({
  logLevel: 'debug',
  timeout: 10000,
  maxInterval: 15000
});

const httpServer = http.createServer(cometdServer.handle);
httpServer.listen(8081, (request, response) => {
});

var channel = cometdServer.createServerChannel('/service/chat');
channel.addListener('message', function (session, channel, message, callback) {
  const request = cometdServer.context.request;
  if (request) {
    console.log("request##", request);
  }
  // Your message handling here.
  console.log("Subscribe##", message);
  // Invoke the callback to signal that handling is complete.
  callback();
});

http.createServer((request, response) => {
  channel.publish("/service/chat", { testKey: "testValue" }, () => {
    response.write("Success");
    response.end();
  });
}).listen(8080);
```

**Comment by sbordet** [comment]
I don't quite understand this complex setup, but:

1. You have one listener to port 8080, which is not bound to CometD.
2. I believe you send a normal HTTP request (not a CometD message) to this listener.
3. From that listener, you perform a server-side publish to CometD channel `/service/chat` (which does not involve any network).

The CometD server never saw a proper CometD request arriving to it, and as such it could not assign `cometdServer.context.request` to any request (there is no request).

**Comment by sbordet** [comment]
Closing as answered.
