### ISSUE TITLE
[Feature Request] Support of phasing out third-party cookies

### ISSUE THREAD

**Issue by nicob-29** [cometd/cometd-nodejs-server#26]
Hi
Google plans soon to activate phasing out third-party cookies
See Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

Doc about phasing out third-party cookies: https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

This feature request requires the possibility to add "Partitioned" to the cookie like Secure.

**Comment by sblecon** [comment]
Hi @sbordet ,
Do you plan to support this?
Next year, It will affect users using Chrome and Edge Chromium.
Best regards,
Stéphane

**Comment by sbordet** [comment]
Yes, cookie specification changes that all browsers agree upon will be supported.
I will look into this in more details in the coming days.

**Comment by nicob-29** [comment]
@sbordet 
Any news, if you plan to support it ? 
Best regards 

Nicolas

**Comment by sblecon** [comment]
Hi @sbordet ,

Just to inform you that based on investigations, we identified an issue with Google Chrome 94 to 100 if the Partitioned cookie is set. In this case, the cookie is ignored by the browser. I suggest to have a flexibility to turn it on or off.

Best regards,
Stéphane
